In [3]:
import pandas as pd
import numpy as np

day_1 = pd.read_sas("Data/DR1TOT_J.xpt")
day_2 = pd.read_sas("Data/DR2TOT_J.xpt")
demo = pd.read_sas("Data/DEMO_J.xpt")

### Przegląd danych

In [4]:
# print(day_1.head())
# print(day_2.head())
# print(demo.head())

# day_1.shape
# day_2.shape
# demo.shape

# day_1.info()
# day_2.info()
# demo.info()

# day_1.describe()
# day_2.describe()
demo.describe()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
count,9254.000000,9254.0,9254.000000,9254.000000,9.254000e+03,5.970000e+02,9254.000000,9254.000000,8704.000000,3.433000e+03,...,8764.000000,9063.000000,4751.000000,9254.000000,9.254000e+03,9254.000000,9254.000000,8763.000000,8780.000000,8.023000e+03
mean,98329.500000,10.0,1.940566,1.507564,3.433423e+01,1.043719e+01,3.233953,3.497190,1.517348,1.074757e+02,...,2.050776,1.472691,2.110714,34670.706829,3.467071e+04,1.517614,140.965853,12.500057,12.202506,2.375490e+00
std,2671.544029,0.0,0.236448,0.499970,2.550028e+01,7.092970e+00,1.277650,1.700961,0.499728,7.061824e+01,...,0.652806,0.721168,0.688517,41356.667327,4.334400e+04,0.499717,4.200801,17.307571,17.155294,1.600291e+00
min,93703.000000,10.0,1.000000,1.000000,5.397605e-79,5.397605e-79,1.000000,1.000000,1.000000,5.397605e-79,...,1.000000,1.000000,1.000000,2571.068712,5.397605e-79,1.000000,134.000000,1.000000,1.000000,5.397605e-79
25%,96016.250000,10.0,2.000000,1.000000,1.100000e+01,4.000000e+00,3.000000,3.000000,1.000000,4.300000e+01,...,2.000000,1.000000,2.000000,13074.433246,1.234731e+04,1.000000,137.000000,6.000000,6.000000,1.040000e+00
50%,98329.500000,10.0,2.000000,2.000000,3.100000e+01,1.000000e+01,3.000000,3.000000,2.000000,1.060000e+02,...,2.000000,1.000000,2.000000,21098.454260,2.105989e+04,2.000000,141.000000,8.000000,8.000000,1.920000e+00
75%,100642.750000,10.0,2.000000,2.000000,5.800000e+01,1.700000e+01,4.000000,4.000000,2.000000,1.660000e+02,...,2.000000,2.000000,3.000000,36923.316352,3.756200e+04,2.000000,145.000000,14.000000,14.000000,3.690000e+00
max,102956.000000,10.0,2.000000,2.000000,8.000000e+01,2.400000e+01,5.000000,7.000000,2.000000,2.390000e+02,...,3.000000,3.000000,3.000000,433085.005262,4.197628e+05,2.000000,148.000000,99.000000,99.000000,5.000000e+00

### Co oznaczają kolumny
Opis kolumn DR1TOT_J https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2017/DataFiles/DR1TOT_J.htm#SEQN  

**SEQN** - id uzytkownika  
**WTDRD1** - Oznacza ile osób w populacji USA reprezentuje dany respondent. 5.397605346934028e-79  jest ich 1063 i to oznacza ze Day 1 dietary recall not done/incomplete.  
**WTDRD2** - Oznacza ile osób w populacji USA reprezentuje dany respondent.  5.397605346934028e-79 jest ich 1002 i to oznacza ze Day 2 dietary recall not done/incomplete.  
**DR1DRSTZ** - Okreslenie jak wiarygodne jest ich raportowania z dnia zywienia. Czemu jest 1,2 4,5 ? Gdzie 3 ? 4 oznacza diete oparta na mleku matki więc nalezalloby to usunąć w dalszych analizach.  
**DR1EXMER** - identyfikator osoby przeprowadzającej wywiad  
**DRABF** - Oznaczenie niemowląt które są na diecie mleka matki  
**DRDINT** - oznakowanie z ilu dni były zebrane dane 1 czy 2  
**DR1DBIH** - liczba dni miedzy dniem spozycia (dietary recall) a wywiadem. Ile dni minelo miedzy dniem którego dotyczy dieta a dniem przeprowadzonego wywiadu. Kolumna istnieje zeby okreslic ryzyko błędu pamięci ? Czyli im wieksza wartosc tym mniej wartosciowe dane  
**DR1DAY** - oznakowanie w jakim dniu jest wspomniana dieta 1-7 Ndz - Sob  
**DR1LANG** - język, którego uzywali respondenci. Tabela na stronie  
**DR1MRESP** - kto głównie odpowiadał na pytania do ankeitowanego poniewaz czesto były wywiady przeprowadzane w domu gdzie była obecna rodzina, lub np respondent nie był ws tanie odpowiedziec na pytanie (np. niemowlę lub bariera jezykowa).  Oznaczenie 1-3 oznacza raczej najbardziej wiarygodne. Tabela na stronie  
**DR1HELP** - kto pomogał przy odpowiedziach. Najczystszy przypadek danych jest 12- No one poniewaz respondent sam odpowiadał bez pomocy. Tabela na stronie

### Oczyszczanie danych - określam dane jako goden zaufania, brak duplikatów, nulli czy niezgodności

In [5]:
# day_1.duplicated().sum() # 0
# day_2.duplicated().sum() # 0
demo.duplicated().sum() # 0

day_1.isnull().sum()

SEQN           0
WTDRD1         0
WTDR2D      1063
DR1DRSTZ       0
DR1EXMER     976
            ...
DRD370T     4366
DRD370TQ    7662
DRD370U     4366
DRD370UQ    8454
DRD370V     4367
Length: 168, dtype: int64

### Buduje warstę SILVER

Wyjaśnienie dodatkowych kolumn:  
**RIAGENDER** - płeć ankietowanego  
**RIDAGEYR** - wiek ankietowanego w latach  
**DR1TKCAL** - określenie w kcal spożycia dietery recall 1  
**DRQSDT3** - Dieta niskosodowa  
**DRQSDT5** - Dieta niskobłonnikowa  
**DRQSDT6** - Dieta wysokobłonnikowa  
**DR1TFIBE** - spozycie błonnika w gm  
**DR1TSODI** - spozycie sodu w gm

In [6]:
# Kolumny, któe mnie interesują do dalszej analizy
silver_demo = demo[[
    "SEQN",
    "RIAGENDR",
    "RIDAGEYR"

]]

silver_day_1 = day_1[[
    "SEQN",
    "DR1DRSTZ",
    "DR1MRESP",
    "DR1HELP",
    "DR1TKCAL",
    "DRQSDT3",
    "DRQSDT5",
    "DRQSDT6",
    "DR1TFIBE",
    "DR1TSODI"
]]

silver_df = silver_day_1.merge(silver_demo, on="SEQN", how="left")

silver_df["age_group"] = pd.cut(
    silver_df["RIDAGEYR"],
    bins=[0, 2, 18, 65, 120],
    labels=["infant", "child", "adult", "senior"]
)

silver_df["quality_score"] = (
    (silver_df["DR1DRSTZ"] == 1).astype(int) +
    (silver_df["DR1MRESP"] == 1).astype(int) +
    (silver_df["DR1HELP"] == 12).astype(int)
)


# Określam flage dla zbyt niskich kcal < 800 normalnych i zbyt wysokich > 5500
silver_df.loc[silver_df["DR1TKCAL"] < 800, "kcal_flag"] = "low_kcal"

silver_df.loc[
    (silver_df["DR1TKCAL"] >= 800) & (silver_df["DR1TKCAL"] <= 5500),
    "kcal_flag"
] = "normal_kcal"

silver_df.loc[silver_df["DR1TKCAL"] > 5500, "kcal_flag"] = "high_kcal"

### Zapisuje silver to postgres

In [9]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:postgres@localhost:5432/diploma_db"
)

# silver_df.to_sql(
#     "nhanes_silver",
#     engine,
#     index=False
# )

### Warstwa gold

In [10]:
'''
Woyodrębniam najbardziej wiarygodne dane
DR1DRSTZ - 1 oznacza ze spełniaja minimalne kryteria i sa reliable
DR1MRESP - 1,2,3  odpowiedzi były przez ankietowanego/ mamę ankietowanego/ tatę ankietowanego
DR1HELP - 12 oznacza ze respondent odpowiadał bez wsparcia osób trzecich
'''
gold_df = silver_df.copy()

 Wartość spożycia błonnika to około 20-40g. Jest to zależne od ilości spożytych kalorii i w przypadku diet wliczających dużą ilość warzyw i owoców drastycznie ono wzrasta. Przyjmuje, że przeciętny człowek powinine zjadać około 2000kcal więc minimalna wartość spożycia błonnika 15g/1000kcal.

In [11]:
gold_df["fiber_per_1000kcal"] = (
    gold_df["DR1TFIBE"] / gold_df["DR1TKCAL"] * 1000
)

gold_df.loc[(gold_df["fiber_per_1000kcal"] < 14), "fiber_flag"] = "low_fiber"

# Dieta niskobłonnikowa
gold_df.loc[
    (gold_df["fiber_per_1000kcal"] < 14) & (gold_df["DRQSDT5"] == 5.0), "fiber_flag"
    ] = "normal_fiber"

gold_df.loc[
    (gold_df["fiber_per_1000kcal"] >= 14) & (gold_df["fiber_per_1000kcal"] <= 30), 
    "fiber_flag"
    ] = "normal_fiber"

gold_df.loc[(gold_df["fiber_per_1000kcal"] > 30), "fiber_flag"] = "high_fiber"

# Dieta wysokobłonnikowa
gold_df.loc[
    (gold_df["fiber_per_1000kcal"] > 30) & (gold_df["DRQSDT6"] == 6.0), "fiber_flag"
    ] = "normal_fiber"

Zapotrzebowanie na sód zwieksza się wraz z zwiększeniem potliwości człowieka. Na ten moment nie mamy danych aby to określić. Minimalna wartość spożycia sodu to 1500 - 2000mg na dobe dla przeciętnego człowieka.

In [12]:
gold_df.loc[(gold_df["DR1TSODI"] < 1500), "sodium_flag"] = "low_sodium"

# Dieta niskosodowa
gold_df.loc[(gold_df["DR1TSODI"] < 1500) & (gold_df["DRQSDT3"] == 3.0)]

gold_df.loc[
    (gold_df["DR1TSODI"] >= 1500) & (gold_df["DR1TSODI"] <= 2000),
    "sodium_flag"
] = "normal_sodium"

gold_df.loc[(gold_df["DR1TSODI"] > 2000), "sodium_flag"] = "high_sodium"

quality_gold_data = gold_df[
    (silver_df["DR1DRSTZ"] == 1) &
    (silver_df["DR1MRESP"].isin([1,2,3])) &
    (silver_df["DR1HELP"] == 12) &
    (silver_df["kcal_flag"] == "normal_kcal")
]

Ustalam parametry dla najbardziej wiarygodnych danych

In [13]:
quality_gold_data = gold_df[
    (silver_df["DR1DRSTZ"] == 1) &
    (silver_df["DR1MRESP"].isin([1,2,3])) &
    (silver_df["DR1HELP"] == 12) &
    (silver_df["kcal_flag"] == "normal_kcal")
]

quality_gold_data

,SEQN,DR1DRSTZ,DR1MRESP,DR1HELP,DR1TKCAL,DRQSDT3,DRQSDT5,DRQSDT6,DR1TFIBE,DR1TSODI,RIAGENDR,RIDAGEYR,age_group,quality_score,kcal_flag,fiber_per_1000kcal,fiber_flag,sodium_flag
1,93704.0,1.0,2.0,12.0,1230.0,NaN,NaN,NaN,5.9,2198.0,1.0,2.000000e+00,infant,2,normal_kcal,4.796748,low_fiber,high_sodium
3,93706.0,1.0,1.0,12.0,1987.0,NaN,NaN,NaN,7.1,3657.0,1.0,1.800000e+01,child,3,normal_kcal,3.573226,low_fiber,high_sodium
4,93707.0,1.0,1.0,12.0,1775.0,NaN,NaN,NaN,10.9,2450.0,1.0,1.300000e+01,child,3,normal_kcal,6.140845,low_fiber,high_sodium
7,93710.0,1.0,2.0,12.0,900.0,NaN,NaN,NaN,6.7,670.0,2.0,5.397605e-79,infant,2,normal_kcal,7.444444,low_fiber,low_sodium
8,93711.0,1.0,1.0,12.0,2840.0,NaN,NaN,6.0,44.5,4382.0,1.0,5.600000e+01,adult,3,normal_kcal,15.669014,normal_fiber,high_sodium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,102951.0,1.0,2.0,12.0,1471.0,NaN,NaN,NaN,8.8,1735.0,1.0,4.000000e+00,child,2,normal_kcal,5.982325,low_fiber,normal_sodium
8700,102953.0,1.0,1.0,12.0,3072.0,NaN,NaN,NaN,57.0,6123.0,1.0,4.200000e+01,adult,3,normal_kcal,18.554688,normal_fiber,high_sodium
8701,102954.0,1.0,1.0,12.0,1757.0,NaN,NaN,NaN,9.5,2993.0,2.0,4.100000e+01,adult,3,normal_kcal,5.406944,low_fiber,high_sodium
8702,102955.0,1.0,1.0,12.0,1256.0,NaN,NaN,NaN,10.2,955.0,2.0,1.400000e+01,child,3,normal_kcal,8.121019,low_fiber,low_sodium
8703,102956.0,1.0,1.0,12.0,1591.0,NaN,NaN,NaN,9.9,2077.0,1.0,3.800000e+01,adult,3,normal_kcal,6.222502,low_fiber,high_sodium

In [14]:
quality_gold_data["fiber_flag"].value_counts()
quality_gold_data["sodium_flag"].value_counts()
quality_gold_data["kcal_flag"].value_counts()

kcal_flag
normal_kcal    5910
Name: count, dtype: int64